### ISSUE TITLE
SEO Configuration

### ISSUE THREAD

**Issue by aagustinconti** [aagustinconti/my_personal_page#6]
We can modify some parameters on the mkdocs.yml to enhanse our visibility on Google Search engine.

```yml
site_name:
site_description:
site_author:
site_keywords:
extra:
   meta:
      author:
      description:
      keywords: 
  ```
